name: ci
on: [push]
jobs:
  go-dependency-producer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - run: go mod tidy
      - run: go run main.go Max
      - run: go build -o app main.go && ./app
      - run: GOPATH="$(pwd):/home/runner/go/bin" go install .
      - run: ./bin/go-dependency-producer MK
      - run: ./bin/go-dependency-producer
